#!/bin/sh
#DESCRIÇÃO: SINCRONIZA OS ARQUIVOS

DIR=$(pwd | awk -F / '{print $(NF-1)}')

if [ -d "$HOME/Sincronizar/$DIR" ]; then
   for file in $@; do 
     echo "[...]Copiando $file"
     cp $file $HOME/Sincronizar/$DIR/
   done
   exec syncthing > /dev/null && echo "Syncthing ativado" || echo "Erro ou synchting já está rodando."
else
  echo "Erro! Não está definido o diretório de destino em ~/Sincronizar"
fi

